### PR TITLE
RetrieveRecordsByDomain method

### PR DESCRIPTION
**Pull request by crackcomm**

### CODE REVIEW

**Comment by pearkes** [comment]
Can you give me a brief description of the purpose of this change?

**Comment by crackcomm** [comment]
It provides a method `RetrieveRecordsByDomain(domain string)` which retrieves all records for the domain.

Edit: It also made code 1 line shorter :)

**Comment by crackcomm** [comment]
I made my own implementation for the v4 API. You can check it out on https://github.com/crackcomm/cloudflare

**Comment by janeczku** [comment]
@crackcomm Ale twoja implementacja rowniez nie ma takiej funkcji... :cry:

**Comment by crackcomm** [comment]
@janeczku w wolnym czasie się tym zajmę: https://github.com/crackcomm/cloudflare/issues/1
jeżeli potrzebujesz takiej funkcji mogę ją dodać

**Comment by crackcomm** [comment]
Now again in English to make @pearkes more comfortable.

@janeczku My implementation won't have this method - too.
After longer consideration I think it should NOT be supported because of many reasons.

After all I made `cf records --domain=...` available in command line tool.

**Comment by janeczku** [comment]
@crackcomm i was not referring to the CLI but rather to have that function as a method of the library. Would have been convenient not to fetch all records in order to modify a single record by domain name.

**Comment by crackcomm** [comment]
@janeczku this problem should be targeted directly to the CloudFlare team, not me.

**Pull request closed without merging**
